
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apaasvhvwoqarnjrwhsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYWFzdmh2d29xYXJuanJ3aHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzcwODIsImV4cCI6MjA2MjY1MzA4Mn0.E7y0in2Gajgm5BES9nIF_-8vnwQ1aYVsxqM6e1W7_bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: {
        'X-Client-Info': 'proposta-flow-manager',
      },
    },
  }
);
